Fix orm for tables in directories
ydb-platform/ydb-sqlalchemy pull request #41
Opened 2024-04-18 13:34 UTC by kabulov

2024-04-19 12:01 UTC, LuckySting requested changes
Reviewed

2024-04-19 12:01 UTC, LuckySting commented on ydb_sqlalchemy/sqlalchemy/__init__.py
> +        if self._has_directories:
**question (blocking)**: In which cases you may want to keep "/" in variable name, as it is always lead to an error?

2024-04-19 12:01 UTC, LuckySting commented on test/test_core.py
> +class TestDirectories(TablesTest):
**suggestion (blocking)**: Let's move it to the `test_orm.py` file near

2024-04-19 13:58 UTC, kabulov commented
we also decided to change `_` to `__` for this effect: `my/dir/my_table -> my__dir__my_table`

2024-04-22 11:18 UTC, rekby approved these changes

2024-04-22 11:19 UTC, merged